### 판매 등록 요청
POST http://localhost:9999/api/sales-order
Content-Type: application/json

{
  "userToken": "epwofj12mivxx85",
  "salesQuantity": 16.30,
  "type": "금 99.99%"
}

### 판매목록 조회
GET http://localhost:9999/api/sales-order/history/list?userToken=fwee112f3gb6bny5
Content-Type: application/json

### 판매 상세 조회
GET http://localhost:9999/api/sales-order/history?orderNo=20240909205003_d6aLfGvLfy
Content-Type: application/json

### 판매내역 삭제
DELETE http://localhost:9999/api/sales-order/history
Content-Type: application/json

{
  "userToken": "epwofj12mivxx85",
  "orderNo": "20240914214310_HMQjk1M3p2"
}
